export enum ACTION_TYPE {
  SET_TOKEN = 'SET_TOKEN',
  SET_PLAYLISTS = 'SET_PLAYLISTS',
  SET_USER = 'SET_USER',
  SET_PLAYER_STATE = 'SET_PLAYER_STATE',
  SET_CURRENTLY_PLAYING = 'SET_CURRENTLY_PLAYING',
  SET_PLAYLIST_ID = 'SET_PLAYLIST_ID',
}
